<?php

namespace App\Models\Admin\SearchInvoice;

use Illuminate\Database\Eloquent\Model;

class SearchInvoice extends Model
{
    protected $table = 'invoices';

    protected $fillable = [

'autopay',
'property_id',
'user_id',
'created_at',
'updated_at',
'LastContractDate',
'InvoiceMgmtCompID',
'InvoiceMgmtCompName',
'InvoiceMgmtAddress1',
'InvoiceMgmtAddress2',
'InvoiceMgmtZipId',
'InvoiceMgmtPhoneNo',
'InvoiceMgmtFaxNo',
'InvoiceMgmtaltNo',
'InvoiceMgmtEmailNo',
'TenantNames',
'TenantAddresss',
'TenantUnitNo',
'TenantZipCodeId',
'InvoiceCode',
'LeaseStartDate',
'invoice_date',
'InvoiceNote',
'Leaseterm',
'Verifier',
'InvMakerId',
'Rent',
'Bonus',
'VKPPercentage',
'FlatRate',
'AmountDueToVKP',
'FirstagentId',
'MONOCount',
'FirstAgentCommPercentage',
'NoNumber',
'Advance',
'MontlyAdvanceCount',
'DueToFirstAgent',
'VKPSplit',
'SecondAgentID',
'DueToSecondAgent',
'FiftyFiftySplit',
'AHIS',
'Legal',
'AdjustCommission',
'NoPay',
'Active',
'APBuyerBrokerPercentage',
'APReferalAmount',
'APPropertyID',
'APAgentName',
'APPaymentCollected',
'APAmountDueToProperty',
'SAPAgentID',
'SAPAgentComRate',
'SAPAgentComAmount',
'SAPComTypes',
'SAPComRate',
'SAPVKPAmount',
'SAPAgentSplit',
'SAPVKPSplit',
'CheckCreatedAgent',
'CheckCreatedsecondAgent',
'CheckCreatedProperty',
'CheckCreatedComm',
'CheckCreatedAdvance',
'AdvanceCreatedCheck',
'EmailSend',
'EmailDate',
'paymentType',
'InvoiceHold',
'InvoiceHoldsecondAgent',
'GiftCard',
'PONO',
'PrintNote',
'bill_country_id',
'bill_state_id',
'bill_city_id',
'bill_zipcode_id',
'tenant_country_id',
'tenant_state_id',
'tenant_city_id',
'tenant_zipcode_id',
    ];
}
